export const demoData = {
    prediction: {
      direction: "up",
      confidence: 78,
      date: "2025-04-19",
    },
    sentimentSummary: {
      bullish: 65,
      bearish: 20,
      neutral: 15,
    },
    stockData: [
      { date: "2025-04-05", price: 185.12, sentiment: 0.2 },
      { date: "2025-04-06", price: 187.45, sentiment: 0.5 },
      { date: "2025-04-07", price: 186.78, sentiment: 0.1 },
      { date: "2025-04-08", price: 184.32, sentiment: -0.3 },
      { date: "2025-04-09", price: 183.67, sentiment: -0.4 },
      { date: "2025-04-10", price: 185.23, sentiment: 0.2 },
      { date: "2025-04-11", price: 188.45, sentiment: 0.6 },
      { date: "2025-04-12", price: 190.12, sentiment: 0.7 },
      { date: "2025-04-13", price: 189.78, sentiment: 0.3 },
      { date: "2025-04-14", price: 191.45, sentiment: 0.5 },
      { date: "2025-04-15", price: 193.67, sentiment: 0.8 },
      { date: "2025-04-16", price: 195.23, sentiment: 0.6 },
      { date: "2025-04-17", price: 194.56, sentiment: 0.2 },
      { date: "2025-04-18", price: 196.78, sentiment: 0.4 },
    ],
    tweets: [
      {
        id: "1",
        author: "StockTrader123",
        text: "$TSLA looking bullish today! Strong support at $190, expecting a breakout soon. #investing",
        date: "2025-04-18",
        sentiment: "bullish",
        retweets: 45,
        replies: 12,
      },
      {
        id: "2",
        author: "MarketAnalyst",
        text: "Tesla production numbers are impressive this quarter. $TSLA could see significant upside.",
        date: "2025-04-18",
        sentiment: "bullish",
        retweets: 78,
        replies: 23,
      },
      {
        id: "3",
        author: "TechInvestor",
        text: "Concerns about $TSLA competition in China. Margins might be under pressure next quarter.",
        date: "2025-04-17",
        sentiment: "bearish",
        retweets: 32,
        replies: 15,
      },
      {
        id: "4",
        author: "EVMarketWatcher",
        text: "Tesla energy division showing strong growth. Often overlooked but could be a major revenue driver for $TSLA.",
        date: "2025-04-17",
        sentiment: "bullish",
        retweets: 56,
        replies: 8,
      },
      {
        id: "5",
        author: "FinanceGuru",
        text: "Just reviewed $TSLA financials. Solid cash position but valuation still concerns me.",
        date: "2025-04-16",
        sentiment: "neutral",
        retweets: 23,
        replies: 19,
      },
      {
        id: "6",
        author: "ElectricFuture",
        text: "New Tesla factory ramping up production faster than expected. Bullish for $TSLA!",
        date: "2025-04-16",
        sentiment: "bullish",
        retweets: 89,
        replies: 31,
      },
      {
        id: "7",
        author: "WallStreetWhiz",
        text: "Selling my $TSLA position today. Technical indicators suggest a pullback is imminent.",
        date: "2025-04-15",
        sentiment: "bearish",
        retweets: 41,
        replies: 27,
      },
      {
        id: "8",
        author: "TeslaOwner",
        text: "Just got my new Model Y and it exceeds all expectations! $TSLA is years ahead of competition.",
        date: "2025-04-15",
        sentiment: "bullish",
        retweets: 112,
        replies: 43,
      },
      {
        id: "9",
        author: "MarketMover",
        text: "$TSLA trading sideways today. Waiting for a clear signal before making a move.",
        date: "2025-04-14",
        sentiment: "neutral",
        retweets: 18,
        replies: 5,
      },
      {
        id: "10",
        author: "InvestmentPro",
        text: "Tesla's AI capabilities are undervalued by the market. $TSLA could see significant upside as FSD improves.",
        date: "2025-04-14",
        sentiment: "bullish",
        retweets: 67,
        replies: 21,
      },
    ],
  }
  